/**
 * Sanitize Mermaid code generated by AI to fix common syntax errors.
 */
export function sanitizeMermaid(code) {
  if (!code) return code

  // Remove backtick code fences
  code = code.replace(/^```(?:mermaid)?\s*/m, '').replace(/\s*```\s*$/m, '').trim()

  const isMindmap = /^mindmap/i.test(code)

  if (isMindmap) {
    // For mindmaps: strip problematic characters from every node label line
    code = code.split('\n').map(line => {
      // Preserve indentation, sanitize content
      const indent = line.match(/^(\s*)/)[1]
      let content = line.slice(indent.length)

      // Si el nodo ya viene envuelto en doble paréntesis (para dibujarse como
      // óvalo, ej. "id((Texto))"), se conserva ese envoltorio y solo se limpia
      // el texto de dentro -- si no, el paso de abajo quitaría TODOS los
      // paréntesis (incluidos los del envoltorio) y se perdería la forma de óvalo.
      const ovalMatch = content.match(/^(\S*)\(\((.*)\)\)\s*$/)
      let prefix = '', suffix = ''
      if (ovalMatch) {
        prefix = `${ovalMatch[1]}((`
        suffix = '))'
        content = ovalMatch[2]
      }

      // Remove superscripts and special math chars that break Mermaid
      content = content
        .replace(/\*\*/g, '')        // **bold** → no soportado en mindmap
        .replace(/\*/g, '')          // *italic* → no soportado en mindmap
        .replace(/_/g, ' ')          // guiones bajos → espacios en etiquetas
        .replace(/[²³¹⁰⁴⁵⁶⁷⁸⁹]/g, '')
        .replace(/·/g, 'x')
        .replace(/[÷×]/g, '/')
        .replace(/[≤≥≠≈]/g, '')
        .replace(/[∑∫∂√∞±]/g, '')
        .replace(/[()]/g, '')        // paréntesis sueltos rompen la sintaxis de nodos
      return indent + prefix + content + suffix
    }).join('\n')
    return code
  }

  // graph TD fixes
  code = code.replace(/^(graph\s+)(T[^DdBb\s]\w*|TO\b|TOP\b)/m, '$1TD')
  code = code.replace(/→/g, '-->')

  // Fix node labels with parentheses inside square brackets
  code = code.replace(/(\w+)\[([^\]]*\([^\]]*)\]/g, (_, id, label) => `${id}["${label}"]`)
  code = code.replace(/(\w+)\(([^)]*\([^)]*\)[^)]*)\)/g, (_, id, label) => `${id}["${label}"]`)

  return code
}
